### ISSUE TITLE
what does ".link()" method does and how to subscribe it?

### ISSUE THREAD

**Issue by birkanozer** [emitter-io/python#21]
As mentioned in the docs .link() method is used to create 2 char links. As I understand that is a shorthand for channels. There is a .publish_with_lik() method but no .subscribe_with_lik() method. How can I utilize links?

**Comment by Florimond** [comment]
You usually subscribe once to a channel, but make multiple publish requests.
Because you publish to a 2-character link without providing the options and the key again and again, you make your life easier, and significantly reduce the size of the messages that have a relatively small payload.

You can subscribe to the channel with the regular `subscribe` method, but there is an option `subscribe: bool` that you can set to True when you create the link, so you are automatically subscribed to the underlying channel when you create the link.
https://github.com/emitter-io/python#link

Please, don't hesitate to provide us with any feedback, and with information about your usecases, so we can thinks of new ways of improving Emitter.

EDIT: @birkanozer I see you have posted more questions on other topics, I'll try to get back to you as soon as possible about those
